### ISSUE TITLE
Sound plays even in VC's that I am not in

### ISSUE THREAD

**Issue by MarOnic12345** [redbaron2k7/videoStartNotifier#1]
Thanks again for taking my request and making this plugin. It works well. However, I did discover an issue with it. After installing the plugin, I noticed that the included sounds would play randomly, even when I wasn't in a VC. I was extremely confused by this until I realized that it must be playing every single time someone turns on/off their webcam in _any_ VC, even ones that I am not in. I even managed to catch it in action and can confirm this is indeed the case.

I would really appreciate it if this could get fixed. Thank you.

**Comment by redbaron2k7** [comment]
> Thanks again for taking my request and making this plugin. It works well. However, I did discover an issue with it. After installing the plugin, I noticed that the included sounds would play randomly, even when I wasn't in a VC. I was extremely confused by this until I realized that it must be playing every single time someone turns on/off their webcam in _any_ VC, even ones that I am not in. I even managed to catch it in action and can confirm this is indeed the case.
> 
> I would really appreciate it if this could get fixed. Thank you.

Hey, not sure how I missed you opening this but the issue has now been resolved. Please update and it should work perfect for you :)
